### PR TITLE
Answer to Part Two

### PR DESCRIPTION
**Pull request by jessicareynolds**

### CODE REVIEW

**Comment by johnny-rice** [comment]
Nice work.

**Comment by sashgems** [comment]
Good work however addition adds the numbers as if they are strings, such as 10 + 2 becomes 102. Subtraction function doesn't work at all :(
Please make changes and add multiplication and division! Thank you!
Any questions message me; Sasha Gemis on slack.

**Comment by johnny-rice** [comment]
@sashgems I am not sure there isn't some confusion.

parseInt is correctly in place on:
https://github.com/jessicareynolds/web-calculator/blob/part-one-answer/index.html

**Comment by johnny-rice** [comment]
@sashgems along those lines I see the expect multiplication and division code.

https://github.com/jessicareynolds/web-calculator/blob/part-two-answer/index.html

**Comment by sashgems** [comment]
Grade: 100% for Part 1 & 2
Awesome Job Jessica and I love the styling and uniqueness to your calculator with the wording for placing each number. 
Homework Explainer Video [if needed b/c it may have a different solution and walk through :) ] Part 1: https://drive.google.com/file/d/1_LGYMz3p34vYgq0yI3Mz1StyYsQNbgzD/view?usp=sharing
Part 2: https://drive.google.com/file/d/1RfjURZDx4a-J68VC5rgHBOGs83njYCba/view?usp=sharing

**Pull request merged**
